env:
  browser: true
  es2021: true
extends: eslint:recommended
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  indent:
    - error
    - tab
  linebreak-style: 0,
    - error
    - windows
  quotes:
    - error
    - double
  semi:
    - error
    - always
